### ISSUE TITLE
Could not load library libcublasLt.so.11

### ISSUE THREAD

**Issue by SamiraJahangiri** [facebookresearch/sapiens#176]
Hello! Thank you in advance for any help!
I installed sapiens and its dependencies from the forked repository to ensure compatibility. But I got this error just for running the demo, using same pretrained checkpoints and inputs in keypoints17.sh
KeyError: 'Adafactor is already registered in optimizer at torch.optim', i

To solve this I downgraded torch to 2.4.1, and torchvision==0.19.1, then i got this Error: libcublasLt.so.11. Here is the full discription of the error. 

Could not load library libcublasLt.so.11. Error: libcublasLt.so.11: cannot open shared object file: No such file or directory
Invalid handle. Cannot load symbol cublasLtCreate
./keypoints17.sh: line 87: 60511 Aborted                 (core dumped) CUDA_VISIBLE_DEVICES=${VALID_GPU_IDS[GPU_ID]} python ${RUN_FILE} ${DETECTION_CONFIG_FILE} ${DETECTION_CHECKPOINT} ${CONFIG_FILE} ${CHECKPOINT} --input "${INPUT}/image_paths_$((i+1)).txt" --output-root="${OUTPUT}" --save-predictions --radius ${RADIUS} --kpt-thr ${KPT_THRES} --thickness ${LINE_THICKNESS}

How can I fix any of these issues?
And this is my nvidia-smi
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A2000 12GB          Off |   00000000:17:00.0 Off |                  Off |
| 30%   26C    P8              4W /   70W |      12MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A2000 12GB          Off |   00000000:73:00.0 Off |                  Off |
| 30%   29C    P8              6W /   70W |      79MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA RTX A2000 12GB          Off |   00000000:A6:00.0 Off |                  Off |
| 30%   28C    P8              4W /   70W |      12MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1886      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A      1886      G   /usr/lib/xorg/Xorg                             64MiB |
|    1   N/A  N/A      2002      G   /usr/bin/gnome-shell                            5MiB |
|    2   N/A  N/A      1886      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by una-dinosauria** [comment]
@SamiraJahangiri I solved the Adafactor issue following the suggestion on this comment: https://github.com/open-mmlab/mmdetection/issues/12008#issuecomment-2449327570

**Comment by SamiraJahangiri** [comment]
Thank you! @una-dinosauria
