### ISSUE TITLE
GPU Memory Issue

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [facebookresearch/sapiens#48]
Hello, thanks so much for your work and code, I am learning a lot. 

I am running the Lite demo for seg (./lite/demo/vis_seg.py) with these arguments (using relative paths for readability here)...

--input ./Sample_Images --output_root ./Sample_Images_Output --fp16 ./seg/sapiens_0.3b_goliath_best_goliath_mIoU_7673_epoch_194_torchscript.pt2

The input image (only one in the sample folder) is of resolution (height x width) (1024, 768), and I am getting this error with an nVidia RTX GPU (24 GB VRAM)

```/home/jamesdickens/miniconda3/envs/sapiens/bin/python /home/jamesdickens/Desktop/Code/sapiens/lite/demo/vis_seg.py --input /home/jamesdickens/Desktop/Code/sapiens/Sample_Images --output_root /home/jamesdickens/Desktop/Code/sapiens/Sample_Images_Output /home/jamesdickens/Desktop/Code/sapiens/seg/sapiens_0.3b_goliath_best_goliath_mIoU_7673_epoch_194_torchscript.pt2 
  0%|          | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/jamesdickens/Desktop/Code/sapiens/lite/demo/vis_seg.py", line 272, in <module>
    main()
  File "/home/jamesdickens/Desktop/Code/sapiens/lite/demo/vis_seg.py", line 242, in main
    result = inference_model(exp_model, batch_imgs, dtype=dtype)
  File "/home/jamesdickens/Desktop/Code/sapiens/lite/demo/vis_seg.py", line 58, in inference_model
    results = model(imgs.to(dtype).cuda())
  File "/home/jamesdickens/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jamesdickens/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/mmseg/models/segmentors/encoder_decoder.py", line 20, in forward
    deconv_layers = decode_head2.deconv_layers
    backbone = self.backbone
    _0 = (deconv_layers).forward((backbone).forward(inputs, ), )
          ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _1 = (dropout).forward((conv_layers).forward(_0, ), )
    return (conv_seg).forward(_1, )
  File "code/__torch__/torch/nn/modules/container.py", line 28, in forward
    _9 = (_1).forward((_0).forward(argument_1, ), )
    _10 = (_4).forward((_3).forward((_2).forward(_9, ), ), )
    _11 = (_7).forward((_6).forward((_5).forward(_10, ), ), )
                        ~~~~~~~~~~~ <--- HERE
    return (_8).forward(_11, )
  File "code/__torch__/mmcv/cnn/bricks/wrappers/___torch_mangle_452.py", line 10, in forward
    argument_1: Tensor) -> Tensor:
    weight = self.weight
    input = torch._convolution(argument_1, weight, None, [2, 2], [1, 1], [1, 1], True, [0, 0], 1, False, False, True, True)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
    return input

Traceback of TorchScript, original code (most recent call last):
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/conv.py(952): forward
/home/rawalk/Desktop/sapiens/cv/mmcv/cnn/bricks/wrappers.py(100): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/container.py(217): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/home/rawalk/Desktop/sapiens/seg/mmseg/models/decode_heads/vit_head.py(129): forward
/home/rawalk/Desktop/sapiens/seg/mmseg/models/segmentors/encoder_decoder.py(242): _forward
/home/rawalk/Desktop/sapiens/seg/mmseg/models/segmentors/base.py(97): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(1088): trace_module
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(820): trace
/home/rawalk/Desktop/sapiens/seg/tools/deployment/pytorch2torchscript.py(118): pytorch2libtorch
/home/rawalk/Desktop/sapiens/seg/tools/deployment/pytorch2torchscript.py(184): <module>
RuntimeError: CUDA out of memory. Tried to allocate 18.00 GiB. GPU 0 has a total capacity of 23.55 GiB of which 14.03 GiB is free. Including non-PyTorch memory, this process has 7.67 GiB memory in use. Of the allocated memory 6.05 GiB is allocated by PyTorch, and 1.17 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) ``

**Comment by rawalkhirodkar** [comment]
Hello, looks like other processing are also occupying the gpu memory. 

Can you terminate them and rerun?

**Comment by JamesMcCullochDickens** [comment]
I just ran it again with another GPU that is using 15 MIB before usage (another 4090 with 24 GB Vram) with torch.cuda.set_device(1) and modifying the --device argument, and I get the same out of memory use error as on gpu 0, which really only has basic display VRAM usage, no other programs are being run that use the GPU.

The code is not modified at all, I am using those run input arguments.  I even tried decreasing the input resolution argument and corresponding image. How much memory should this torchscript file be using? I would think 24 GB is enough for a single image right?

I use these gpus with my driver for many other projects so I know its not a driver/pytorch issue. Any ideas? Thanks for your help. Does it matter that I am using cuda 11.8?

**Comment by rawalkhirodkar** [comment]
24 gb is more than enough. 

The only thing that pops out to me is that you are using --fp16 in your command for the torchscript model. Can you remove this flag and try again?

**Comment by JamesMcCullochDickens** [comment]
@rawalkhirodkar same error.

I am going to try to rebuild the whole project with cuda 12.1 to rule that out at some point in the next coming days.

**Comment by rawalkhirodkar** [comment]
@JamesMcCullochDickens I see. 
Ideal setting would be torch2.2+ and cuda12+, which is what we have extensively tested against. 

I still don't think the cuda version should be an issue, but I can't point to other things as of now. Let me know how it goes.

**Comment by JamesMcCullochDickens** [comment]
I fixed it, set the --batch_size param to 1, it defaulted to 32, not sure if it duplicates the other images or just zero pads, but now the result is all messed up ahaha
![Person](https://github.com/user-attachments/assets/79131197-5564-4f92-b2d7-70fdc378c62e)

**Comment by JamesMcCullochDickens** [comment]
With the 1B model I got, good to go! Thanks.

![Person](https://github.com/user-attachments/assets/e34f67ca-0b1b-4f8a-8479-b5e1be113790)
